# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import logs_pb2 as logs__pb2


class LogsStub(object):
  """The Logs service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Print = channel.unary_unary(
        '/logs.Logs/Print',
        request_serializer=logs__pb2.GetRecentRequest.SerializeToString,
        response_deserializer=logs__pb2.GetRecentResponse.FromString,
        )


class LogsServicer(object):
  """The Logs service definition.
  """

  def Print(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LogsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Print': grpc.unary_unary_rpc_method_handler(
          servicer.Print,
          request_deserializer=logs__pb2.GetRecentRequest.FromString,
          response_serializer=logs__pb2.GetRecentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'logs.Logs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
